import { all_routes } from "../../../feature-module/routes/all_routes";

export const header = [
  {
    tittle: "Home",
    base: "index",
    icon: "expand_more",
    showAsTab: false,
    separateRoute: true,
    menu: [
      {
        menuValue: "Home 1",
        img: "assets/img/home/home-01.jpg",
        route: all_routes.index,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Home 2",
        img: "assets/img/home/home-02.jpg",
        route: all_routes.index2,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Home 3",
        img: "assets/img/home/home-03.jpg",
        route: all_routes.index3,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Coming Soon",
        img: "assets/img/home/coming-soon.jpg",
        route: "#",
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Listing",
    base: "listings",
    icon: "expand_more",
    showAsTab: false,
    separateRoute: false,
    menu: [
      {
        menuValue: "Buy Property",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Buy Grid",
            route: all_routes.buyPropertyGrid,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Buy List",
            route: all_routes.buyPropertyList,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Buy Grid with Sidebar",
            route: all_routes.buyPropertyGridSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Buy List with Sidebar",
            route: all_routes.buyPropertyListSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Buy Grid with map",
            route: all_routes.buyGridMap,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Buy List with map",
            route: all_routes.buyListMap,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Buy Details",
            route: all_routes.buyDetails,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        menuValue: "Rent Property",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Rent Grid",
            route: all_routes.rentPropertyGrid,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Rent List",
            route: all_routes.rentPropertyList,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Rent Grid with Sidebar",
            route: all_routes.rentPropertyGridSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Rent List with Sidebar",
            route: all_routes.rentPropertyListSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Rent Grid with map",
            route: all_routes.rentGridMap,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Rent List with map",
            route: all_routes.rentListMap,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Rent Details",
            route: all_routes.rentDetails,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
    ],
  },
  {
    tittle: "Agent",
    showAsTab: false,
    separateRoute: false,
    base: "agent",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Agent Grid",
        route: all_routes.agentGrid,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Agent List",
        route: all_routes.agentList,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Agent Grid with Sidebar",
        route: all_routes.agentGridSidebar,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Agent List with Sidebar",
        route: all_routes.agentListSidebar,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Agent Details",
        route: all_routes.agentDetails,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Agency",
    showAsTab: false,
    separateRoute: false,
    base: "agency",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Agency Grid",
        route: all_routes.agencyGrid,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Agency List",
        route: all_routes.agencyList,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Agency Grid with Sidebar",
        route: all_routes.agencyGridSidebar,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Agency List with Sidebar",
        route: all_routes.agencyListSidebar,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Agency Details",
        route: all_routes.agencyDetails,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Pages",
    showAsTab: false,
    separateRoute: false,
    base: "pages",
    icon: "expand_more",
    menu: [
      {
        menuValue: "About Us",
        route: all_routes.aboutUs,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Authentication",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Sign Up",
            route: all_routes.signup,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Sign In",
            route: all_routes.signin,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Forgot Password",
            route: all_routes.forgotPassword,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Reset Password",
            route: all_routes.resetPassword,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
       {
        menuValue: "Invoice Details",
        route: all_routes.invoiceDetails,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Contact Us",
        route: all_routes.contactUs,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Wishlist",
        route: all_routes.wishlist,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Error Page",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Error 404",
            route: all_routes.error404,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Error 500",
            route: all_routes.error500,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
         
        ],
      },
       {
        menuValue: "Pricing",
        route: all_routes.pricing,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "FAQ",
        route: all_routes.faq,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Gallery",
        route: all_routes.gallery,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Our Team",
        route: all_routes.ourTeam,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Testimonials",
        route: all_routes.testimonial,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Terms & Conditions",
        route: all_routes.termsCondition,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Privacy Policy",
        route: all_routes.privacyPolicy,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Maintenance",
        route: all_routes.maintenance,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
       {
        menuValue: "Coming Soon",
        route: all_routes.comingSoon,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
   {
    tittle: "Blog",
    showAsTab: false,
    separateRoute: false,
    base: "agency",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Blog List",
        route: all_routes.blogList,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Blog Grid",
        route: all_routes.blogGrid,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Blog Details",
        route: all_routes.blogDetails,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
];
