import { all_routes } from "../../../feature-module/routes/all_routes";

export const header = [
  {
    tittle: "Inicio",
    base: "index",
    icon: "",
    showAsTab: false,
    separateRoute: false,
    menu: [
      {
        menuValue: "Inicio",
        route: all_routes.index,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Propiedades",
    base: "listings",
    icon: "expand_more",
    showAsTab: false,
    separateRoute: false,
    directRoute: all_routes.propiedades,
    menu: [
      {
        menuValue: "Comprar propiedad",
        route: all_routes.buyPropertyGridSidebar,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Alquilar propiedad",
        route: all_routes.rentPropertyGridSidebar,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Agentes",
    showAsTab: false,
    separateRoute: false,
    directRoute: all_routes.agentGrid,
    base: "agent",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Agentes en cuadrícula",
        route: all_routes.agentGrid,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Detalles del agente",
        route: all_routes.agentDetails,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    // Oculto en el navbar a pedido del usuario. Se mantienen los datos para
    // poder reactivar alguna de las variantes (Páginas) en el futuro.
    hidden: true,
    tittle: "Páginas",
    showAsTab: false,
    separateRoute: false,
    base: "pages",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Sobre nosotros",
        route: all_routes.aboutUs,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Autenticación",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Registrarse",
            route: all_routes.signup,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Iniciar sesión",
            route: all_routes.signin,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Olvidé mi contraseña",
            route: all_routes.forgotPassword,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Restablecer contraseña",
            route: all_routes.resetPassword,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        menuValue: "Contáctanos",
        route: all_routes.contactUs,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Lista de deseos",
        route: all_routes.wishlist,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Preguntas frecuentes",
        route: all_routes.faq,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Galería",
        route: all_routes.gallery,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Nuestro equipo",
        route: all_routes.ourTeam,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Testimonios",
        route: all_routes.testimonial,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Términos y condiciones",
        route: all_routes.termsCondition,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Política de privacidad",
        route: all_routes.privacyPolicy,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
];
