// Auto-generated by scripts/write-app-version.js. Do not edit by hand.
export const APP_VERSION = 'v1.270';
export const APP_VERSION_MAJOR = 1;
export const APP_COMMIT_COUNT = 270;
export const APP_BUILD_DATE = '2026-08-04T17:25:19.553Z';

export default APP_VERSION;
