// Auto-generated by scripts/write-app-version.js. Do not edit by hand.
export const APP_VERSION = 'v1.271';
export const APP_VERSION_MAJOR = 1;
export const APP_COMMIT_COUNT = 271;
export const APP_BUILD_DATE = '2026-08-04T18:41:51.241Z';

export default APP_VERSION;
