// Auto-generated by scripts/write-app-version.js. Do not edit by hand.
export const APP_VERSION = 'v1.263';
export const APP_VERSION_MAJOR = 1;
export const APP_COMMIT_COUNT = 263;
export const APP_BUILD_DATE = '2026-06-22T00:45:09.714Z';

export default APP_VERSION;
