// Auto-generated by scripts/write-app-version.js. Do not edit by hand.
export const APP_VERSION = 'v1.281';
export const APP_VERSION_MAJOR = 1;
export const APP_COMMIT_COUNT = 281;
export const APP_BUILD_DATE = '2026-08-20T20:58:34.724Z';

export default APP_VERSION;
