// Auto-generated by scripts/write-app-version.js. Do not edit by hand.
export const APP_VERSION = 'v1.262';
export const APP_VERSION_MAJOR = 1;
export const APP_COMMIT_COUNT = 262;
export const APP_BUILD_DATE = '2026-06-22T00:08:25.747Z';

export default APP_VERSION;
