// Auto-generated by scripts/write-app-version.js. Do not edit by hand.
export const APP_VERSION = 'v1.176';
export const APP_VERSION_MAJOR = 1;
export const APP_COMMIT_COUNT = 176;

export default APP_VERSION;
