// Auto-generated by scripts/write-app-version.js from changelog.json (repo root).
// Do not edit by hand: edit changelog.json instead.
export const CHANGELOG_ENTRIES = [
  {
    "date": "2026-06-12",
    "title": "Carga de propiedades sin campos obligatorios",
    "items": [
      {
        "type": "mejora",
        "text": "El formulario de nueva propiedad ya no exige campos obligatorios: podés guardar con los datos que tengas a mano y completar el resto cuando quieras, sin trabas en el flujo de trabajo."
      },
      {
        "type": "mejora",
        "text": "Si guardás sin título, el sistema arma uno automáticamente con el tipo de propiedad, la operación y el barrio (por ejemplo: \"Departamento en Venta · Palermo\")."
      }
    ]
  },
  {
    "date": "2026-06-12",
    "title": "Compartir propiedades por WhatsApp",
    "items": [
      {
        "type": "arreglo",
        "text": "Los links de propiedades que se copian desde el panel ahora muestran la vista previa completa al compartirlos por WhatsApp, también desde iPhone: foto de portada grande arriba y, debajo, el precio, la dirección, los ambientes, los amenities y la descripción."
      }
    ]
  },
  {
    "date": "2026-06-11",
    "title": "Carga de propiedades más simple y ubicación exacta",
    "items": [
      {
        "type": "mejora",
        "text": "El alta y la edición de propiedades ahora son una sola pantalla: los datos de la propiedad y la asignación del cliente quedaron juntos, sin tener que pasar por un \"paso 2\" aparte."
      },
      {
        "type": "nuevo",
        "text": "La dirección se carga en dos campos separados, calle y altura (número). Al completar la altura, el mapa ubica el pin en la posición exacta de la propiedad."
      }
    ]
  },
  {
    "date": "2026-06-11",
    "title": "Consultas del sitio web y portales inmobiliarios",
    "items": [
      {
        "type": "nuevo",
        "text": "Nueva sección Consultas: ahora podés ver y hacer seguimiento de todas las consultas que llegan desde el sitio web, con estados para saber cuáles ya fueron respondidas."
      },
      {
        "type": "nuevo",
        "text": "Integraciones con portales: las propiedades pueden publicarse automáticamente en 12 portales inmobiliarios (Zonaprop, Argenprop, Proppit y más) mediante feeds que se actualizan solos."
      },
      {
        "type": "arreglo",
        "text": "Solucionamos un error que dejaba el panel de administración fuera de servicio."
      }
    ]
  },
  {
    "date": "2026-06-09",
    "title": "Operaciones y comisiones",
    "items": [
      {
        "type": "arreglo",
        "text": "Las comisiones ahora se calculan correctamente según quién las mire: el administrador ve el total y cada agente ve solo lo suyo."
      },
      {
        "type": "mejora",
        "text": "Al editar una operación se abre el mismo formulario completo que al crearla, con todos los datos cargados."
      }
    ]
  },
  {
    "date": "2026-06-08",
    "title": "Historial de operaciones y fotos renovadas",
    "items": [
      {
        "type": "nuevo",
        "text": "Las operaciones ahora se pueden editar y eliminar, y hay una tabla con el historial completo."
      },
      {
        "type": "mejora",
        "text": "Las fotos de las propiedades se muestran en un nuevo visor tipo presentación, más grande y moderno."
      }
    ]
  },
  {
    "date": "2026-06-07",
    "title": "Tours virtuales 360",
    "items": [
      {
        "type": "mejora",
        "text": "Los tours 360 ahora tienen botón de pantalla completa (estilo YouTube) y se ven mejor integrados en la página."
      }
    ]
  },
  {
    "date": "2026-06-06",
    "title": "Filtros por agente y mejoras en WhatsApp",
    "items": [
      {
        "type": "nuevo",
        "text": "Filtro por agente en Propiedades y en Clientes: elegí un agente y mirá solo lo que le pertenece."
      },
      {
        "type": "nuevo",
        "text": "En la Bandeja de WhatsApp ahora se pueden eliminar conversaciones."
      },
      {
        "type": "mejora",
        "text": "La configuración de WhatsApp se movió a la página de Integraciones para tener todo en un solo lugar."
      }
    ]
  }
];

export default CHANGELOG_ENTRIES;
