// Auto-generated by scripts/write-app-version.js from changelog.json (repo root).
// Do not edit by hand: edit changelog.json instead.
// Filtrado para "agents": solo las novedades que le incumben a esta app.
export const CHANGELOG_ENTRIES = [
  {
    "date": "2026-08-21",
    "title": "En el alta de cliente ya se pueden marcar varias propiedades",
    "items": [
      {
        "type": "nuevo",
        "text": "Cuando das de alta un cliente que consultó por varias propiedades, ahora las podés marcar todas en el mismo formulario. Antes entraba una sola: al elegir la segunda se borraba la primera. Las que agregás quedan listadas y se sacan una por una con la cruz."
      },
      {
        "type": "nuevo",
        "text": "Cada propiedad que marcás en el alta queda registrada automáticamente como \"propiedad de interés\" del cliente, así que aparece en las métricas y en las sugerencias sin que tengas que cargarla otra vez a mano."
      },
      {
        "type": "mejora",
        "text": "El buscador del alta encuentra propiedades de toda la inmobiliaria, no solo las tuyas. Si el cliente consultó por algo que captó un compañero, lo podés dejar declarado igual. La primera que agregues queda marcada como \"Primera\", que es la que se usa al programar un recontacto."
      }
    ]
  },
  {
    "date": "2026-08-20",
    "title": "Todos los agentes ven ahora el portfolio completo de la inmobiliaria",
    "items": [
      {
        "type": "mejora",
        "audiencia": "agente",
        "text": "Ya no ves solo tus captaciones: en \"Propiedades de la Inmobiliaria\" aparece todo el portfolio, con la ficha completa de cada propiedad, sus fotos y el agente a cargo. Si un cliente tuyo pregunta por algo que captó un compañero, lo podés abrir y contestarle en el momento, sin tener que pedirle los datos a nadie."
      },
      {
        "type": "mejora",
        "audiencia": "agente",
        "text": "\"Mis Captaciones\" sigue mostrando solo las tuyas, que son las que podés editar, despublicar o borrar. Las propiedades de otros agentes se abren en modo lectura: las consultás, pero no se tocan."
      }
    ]
  },
  {
    "date": "2026-08-16",
    "title": "El buscador de la barra superior ahora se ve como un buscador",
    "items": [
      {
        "type": "mejora",
        "text": "El botón de búsqueda dejó de parecer un ícono suelto: ahora es un campo con el texto \"Buscar…\" y el atajo de teclado a la vista (Ctrl K, o ⌘K si usás Mac). En pantallas chicas se achica a un botón redondo para no ocupar lugar."
      },
      {
        "type": "mejora",
        "text": "El cuadro de resultados quedó más prolijo y abajo aparece qué teclas usar: flechas para moverse, Enter para abrir y Esc para cerrar."
      }
    ]
  },
  {
    "date": "2026-08-16",
    "title": "Llega el motor de recomendaciones: cruza tu cartera con lo que pide cada cliente",
    "items": [
      {
        "type": "nuevo",
        "audiencia": "agente",
        "text": "Si las sugerencias aparecen con textos cortos y secos, es porque falta que administración cargue la clave de OpenAI. Los puntajes y el orden ya son correctos; lo que falta es la explicación escrita."
      },
      {
        "type": "nuevo",
        "text": "En la ficha de cada cliente aparece \"Propiedades sugeridas\": el sistema cruza toda la cartera con lo que ese cliente pidió, le pone un puntaje del 1 al 100 y explica en palabras por qué cada propiedad le sirve. También dice qué NO cumple, para que puedas anticiparlo antes de la visita."
      },
      {
        "type": "nuevo",
        "text": "En la ficha de cada propiedad aparece \"Clientes para esta propiedad\". Cuando entra una captación nueva, ya no hace falta acordarse de quién estaba buscando eso: el sistema te lo dice."
      },
      {
        "type": "nuevo",
        "text": "Cada sugerencia trae un mensaje de WhatsApp ya escrito para mandarle al cliente, y botones para marcar la visita o descartarla. Lo que descartás no se vuelve a sugerir."
      },
      {
        "type": "nuevo",
        "audiencia": "agente",
        "text": "Cuando se carga una propiedad nueva o cambia de precio, llega un aviso con todos tus clientes que la estaban buscando, en un solo mensaje en vez de uno por cliente."
      },
      {
        "type": "nuevo",
        "text": "La zona de interés del cliente ahora acepta varias zonas en vez de una sola. La primera es la principal."
      }
    ]
  },
  {
    "date": "2026-08-15",
    "title": "Barra superior nueva: avisos que avisan de verdad",
    "items": [
      {
        "type": "arreglo",
        "text": "Los contadores de la barra superior ahora cuentan bien. Antes el número de tareas incluía las que ya estaban terminadas o canceladas y nunca bajaba, y las citas canceladas seguían sumando."
      },
      {
        "type": "arreglo",
        "text": "Se terminaron los avisos repetidos. Una consulta del sitio contaba a la vez en Consultas y en Alertas, y una tarea vencida volvía a avisar todos los días. Ahora cada cosa avisa una sola vez y en un solo lugar."
      },
      {
        "type": "arreglo",
        "text": "Al completar o cancelar una tarea, su aviso desaparece de la campana en el momento. Antes seguía ahí hasta que alguien borraba la tarea."
      },
      {
        "type": "arreglo",
        "text": "El panel de Alertas ya no marca todo como leído apenas se abre: ahora se ve cuáles son nuevas y cada una se marca al abrirla, o todas juntas con el botón."
      },
      {
        "type": "arreglo",
        "text": "El botón \"Ver más\" de las alertas ahora abre la pantalla correcta. Varias llevaban a direcciones que no existían y terminaban devolviendo al inicio o a la pantalla de ingreso."
      },
      {
        "type": "arreglo",
        "text": "La foto y el nombre del perfil se actualizan al instante después de guardarlos. Antes había que recargar la página para verlos cambiados."
      },
      {
        "type": "arreglo",
        "text": "Se dejaron de mostrar los avisos del navegador en cada recarga de página."
      },
      {
        "type": "nuevo",
        "text": "Buscador general con Ctrl+K: encontrá una propiedad por título o dirección, un cliente por nombre, mail o teléfono, o una operación, desde cualquier pantalla."
      },
      {
        "type": "nuevo",
        "text": "Botón \"+\" para crear una propiedad, un cliente, una cita o una tarea sin salir de donde estás."
      },
      {
        "type": "nuevo",
        "text": "El avatar ahora abre un menú con Mi perfil, Seguridad, modo claro/oscuro y Cerrar sesión. Antes no había forma de cerrar sesión desde la barra superior."
      },
      {
        "type": "nuevo",
        "text": "Los agentes ven su próxima cita con hora y lugar en la barra superior, y se resalta cuando falta menos de una hora."
      },
      {
        "type": "nuevo",
        "text": "Las notificaciones ahora llegan al celular aunque tengas la app cerrada. Si la tenés abierta no se duplican: se actualizan los números directamente."
      },
      {
        "type": "mejora",
        "text": "Tareas y Citas quedaron separadas, cada una con su propio botón, y muestran sólo lo urgente: lo vencido, lo de hoy y las citas de las próximas 24 horas."
      },
      {
        "type": "mejora",
        "text": "Propiedades salió de la barra superior: su lugar está en el menú lateral. El número que mostraba era el total de propiedades disponibles, no algo pendiente de resolver."
      },
      {
        "type": "mejora",
        "text": "El trofeo de Logros salió de la barra superior de agentes. Los logros siguen completos en su propia pantalla."
      },
      {
        "type": "mejora",
        "text": "Las consultas del sitio ahora muestran la foto de la propiedad consultada en lugar de un ícono."
      },
      {
        "type": "mejora",
        "text": "Los desplegables se cierran con Escape o tocando de nuevo el mismo botón, y en el celular ya no se salen de la pantalla."
      }
    ]
  },
  {
    "date": "2026-08-14",
    "title": "Limpieza: se van las pantallas que no hacían nada",
    "items": [
      {
        "type": "arreglo",
        "text": "Los gráficos de la ficha de cliente ahora muestran datos reales de la base. Antes varias barras y líneas traían números de ejemplo que no salían de ningún lado."
      },
      {
        "type": "arreglo",
        "text": "Se quitaron de la ficha de cliente los recuadros de sesiones web, dispositivos, fuente de tráfico y acciones en la web. Esa información nunca se midió, así que los números que mostraban eran inventados."
      },
      {
        "type": "arreglo",
        "text": "El gráfico de evolución de leads y conversiones del panel de clientes ahora se calcula con las altas reales de cada mes."
      },
      {
        "type": "nuevo",
        "text": "Administración ya tiene la pantalla de Automatización completa, la misma que usaban los agentes: crear reglas desde plantillas, activarlas, pausarlas, probarlas y ver sus estadísticas."
      },
      {
        "type": "mejora",
        "text": "Se retiraron las pantallas de Campañas, Email Marketing, Workflows, Analítica de Marketing, Roles y Permisos y Configuración. Estaban a medio hacer: mostraban datos de ejemplo y sus botones no guardaban nada. Vuelven cuando estén terminadas."
      },
      {
        "type": "mejora",
        "text": "En el menú del perfil de administración, Configuración se reemplazó por Seguridad, que sí permite cambiar la contraseña y activar la verificación en dos pasos."
      },
      {
        "type": "mejora",
        "text": "En el panel de agentes, el menú del perfil ahora dice Consultas y Agenda, que es adonde llevaba realmente."
      },
      {
        "type": "mejora",
        "text": "Se quitó el botón de adjuntar archivos del chat de WhatsApp, que solo avisaba que no estaba disponible."
      },
      {
        "type": "mejora",
        "text": "Se limpió el menú del sitio público: ya no aparecen las páginas de demostración que venían con la plantilla (factura, errores 404 y 500, mantenimiento, próximamente y precios)."
      },
      {
        "type": "mejora",
        "text": "El panel de administración carga bastante más rápido: se eliminaron las pantallas de demostración que quedaban de la plantilla original y que se descargaban en cada visita."
      }
    ]
  },
  {
    "date": "2026-08-08",
    "title": "El panel de agentes también centraliza sus consultas",
    "items": [
      {
        "type": "nuevo",
        "text": "En el panel de agentes, la burbuja de mensajes ahora abre un desplegable con el adelanto de las consultas recibidas, igual que en administración. Cada agente ve las consultas de sus propias propiedades."
      },
      {
        "type": "nuevo",
        "text": "Las consultas se pueden marcar como leídas o sin leer, filtrar por pendientes y eliminar de la base de datos, con el mismo funcionamiento que en administración."
      },
      {
        "type": "mejora",
        "text": "Se quitó la sección Mensajería del menú de agentes. Todo lo que llega del sitio se atiende desde Consultas."
      },
      {
        "type": "mejora",
        "text": "Se eliminó el chat interno entre agentes, que no se estaba usando."
      }
    ]
  },
  {
    "date": "2026-08-08",
    "title": "Consultas del sitio en un solo lugar",
    "items": [
      {
        "type": "nuevo",
        "text": "La burbuja de mensajes de la barra superior ahora abre un desplegable con el adelanto de las últimas consultas, igual que el resto de los iconos de notificaciones. Desde ahí se abre cada una o se marcan todas como leídas."
      },
      {
        "type": "nuevo",
        "text": "Los mensajes del formulario de contacto de la web ahora aparecen en Consultas, junto a las consultas de propiedades y las solicitudes de visita. Antes se guardaban pero no se mostraban en ningún lado."
      },
      {
        "type": "nuevo",
        "text": "Cada consulta se puede marcar como leída o sin leer, de a una o todas juntas, y las pendientes quedan resaltadas."
      },
      {
        "type": "nuevo",
        "text": "Ahora se pueden eliminar consultas con el botón del tacho. El borrado es definitivo: la consulta se saca de la base de datos y no se puede recuperar, por eso pide confirmación antes."
      },
      {
        "type": "mejora",
        "text": "Se quitó la sección Mensajería del menú lateral. Todo lo que llega del sitio se atiende desde Consultas, que ahora también permite filtrar por origen y ver solo las pendientes."
      },
      {
        "type": "arreglo",
        "text": "El contador rojo de la burbuja marcaba mensajes que después no se podían encontrar, porque llevaba a la ventana de WhatsApp. Ahora el número coincide siempre con lo que se ve en el desplegable."
      },
      {
        "type": "mejora",
        "text": "Se quitó la ventana de WhatsApp, que no se estaba usando. Las conversaciones quedan guardadas por si más adelante se vuelve a activar."
      },
      {
        "type": "mejora",
        "text": "Se eliminó el chat interno entre agentes, que no se estaba usando."
      }
    ]
  },
  {
    "date": "2026-08-06",
    "title": "Detalle de propiedades abre desde arriba",
    "items": [
      {
        "type": "arreglo",
        "text": "Al abrir una propiedad desde la grilla, la página de detalle ahora comienza arriba correctamente en lugar de conservar el scroll del listado."
      }
    ]
  },
  {
    "date": "2026-08-04",
    "title": "Mensajería más clara para admin y agentes",
    "items": [
      {
        "type": "mejora",
        "text": "El menú lateral ahora muestra Mensajería como bandeja central de conversaciones, sin separar la experiencia como una ventana exclusiva de WhatsApp."
      },
      {
        "type": "mejora",
        "text": "Las notificaciones de mensajes en el panel de agentes ahora llevan directamente a la bandeja de Mensajería, para responder desde el lugar correcto."
      },
      {
        "type": "nuevo",
        "text": "El panel de agentes ahora también muestra el botón de Novedades, con el mismo historial de cambios visible para administración."
      },
      {
        "type": "mejora",
        "text": "Se quitó el botón manual de prueba de celebración del panel de agentes, manteniendo las celebraciones reales de logros y recompensas."
      },
      {
        "type": "nuevo",
        "text": "En la bandeja de Mensajería de administración ahora hay una acción visible para eliminar conversaciones desde el chat seleccionado."
      }
    ]
  },
  {
    "date": "2026-08-04",
    "title": "Clientes mejor clasificados según su perfil comercial",
    "items": [
      {
        "type": "mejora",
        "text": "El alta y edición de clientes ahora se adapta al tipo de cliente seleccionado. Compradores, propietarios, inversores e inquilinos tienen campos específicos para registrar la información que realmente necesita el equipo comercial."
      },
      {
        "type": "mejora",
        "text": "La sección que antes era siempre \"Preferencias de búsqueda\" ahora cambia según el perfil: preferencias de compra para compradores, datos de la propiedad para propietarios, perfil de inversión para inversores y preferencias de alquiler para inquilinos."
      },
      {
        "type": "nuevo",
        "text": "Para propietarios se pueden cargar datos propios de la propiedad, como operación esperada, valor pretendido, estado, documentación, superficies y antigüedad. Para inversores se suman objetivo, rentabilidad esperada, horizonte y tolerancia al riesgo. Para inquilinos se agregan datos como presupuesto mensual, garantía, fecha de mudanza, mascotas, amoblado y expensas máximas."
      },
      {
        "type": "nuevo",
        "text": "Cuando el tipo de propiedad es Lote, el CRM ahora permite indicar el tipo de lote: unifamiliar, comercial, multifamiliar, artesanal, administrativo, hotelero o residenciales multifamiliares, además de superficie, frente, fondo, zonificación y servicios."
      },
      {
        "type": "mejora",
        "text": "Las fichas de clientes también muestran la información comercial con títulos y datos acordes al perfil, para que administradores y agentes trabajen con registros más claros, completos y útiles."
      }
    ]
  },
  {
    "date": "2026-08-04",
    "title": "Agenda CRM más inteligente y conectada con clientes",
    "items": [
      {
        "type": "nuevo",
        "text": "La agenda del CRM ahora permite abrir y editar cada cita directamente desde el calendario, sin cambiar de pantalla. Al seleccionar un día y hacer clic sobre una cita, se abre un recuadro de edición integrado al diseño actual para actualizar fecha, horario, cliente, propiedad, responsable, estado, ubicación y detalles de la reunión o visita."
      },
      {
        "type": "mejora",
        "text": "El calendario y el historial de cada cliente ahora trabajan conectados. Cuando se agenda una visita o reunión para un cliente, esa actividad queda reflejada en su registro de interacciones; y cuando se registra una visita agendada desde la ficha del cliente, la cita aparece automáticamente en la agenda."
      },
      {
        "type": "mejora",
        "text": "Esta mejora ayuda a que el equipo comercial tenga una visión más clara y confiable de cada seguimiento: la agenda muestra qué hay que hacer, mientras que la ficha del cliente conserva el historial completo de lo ocurrido."
      },
      {
        "type": "mejora",
        "text": "Al editar una cita vinculada a un cliente, el CRM mantiene la información alineada entre agenda e interacciones, reduciendo tareas duplicadas y evitando diferencias entre lo planificado y lo registrado."
      }
    ]
  },
  {
    "date": "2026-07-12",
    "title": "Clientes en stand by dentro del funnel",
    "items": [
      {
        "type": "nuevo",
        "text": "El funnel de clientes ahora incluye la columna Congelado para separar los casos que quedan en stand by sin marcarlos como perdidos ni ganados."
      }
    ]
  },
  {
    "date": "2026-07-02",
    "title": "Arreglo: pantalla en blanco al traducir la página",
    "items": [
      {
        "type": "arreglo",
        "text": "Solucionamos un error que hacía que la app se cerrara o quedara en blanco cuando el navegador (Chrome/Edge) traducía la página automáticamente. Ahora el sitio se identifica correctamente en español y se evita esa traducción, que era la causa del problema."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Agentes: centro de mando con Score de Desempeño",
    "items": [
      {
        "type": "nuevo",
        "text": "El panel de Agentes ahora es el centro de mando del equipo: incorpora un Score de Desempeño (0-100) por agente que combina captaciones, ventas, actividad, calidad de carga de propiedades, uso de la app, conversión y fidelización."
      },
      {
        "type": "nuevo",
        "text": "Nuevo Ranking de Desempeño que ordena a los agentes por su Score, con el desglose por categoría y atajo al detalle de cada uno."
      },
      {
        "type": "nuevo",
        "text": "Se mide el uso de la app: tiempo activo, cantidad de logins, días activos y racha de cada agente, visibles en el panel y en su ficha."
      },
      {
        "type": "nuevo",
        "text": "Nueva métrica de Calidad de Carga: mide qué tan completas están las publicaciones (fotos, descripción, video, tour 360°, ubicación en el mapa y dirección)."
      },
      {
        "type": "mejora",
        "text": "Recompensas se fusionó dentro de Agentes (pestaña \"Ranking & Recompensas\"). El ranking, tiers, premios y la configuración ahora viven en un solo lugar; se quitó la entrada \"Recompensas\" del menú."
      },
      {
        "type": "mejora",
        "text": "La ficha de cada agente ahora muestra su Score con desglose, su uso de la app y un resumen de recompensas (categoría anual, captaciones, facturación, fidelización y pre-listing)."
      },
      {
        "type": "nuevo",
        "text": "Desde Configuración se puede ajustar la ponderación de cada categoría del Score y sus metas, para adaptarlo a las prioridades del equipo."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Menú del sitio con estilo glass",
    "items": [
      {
        "type": "mejora",
        "text": "Los botones del menú principal (Inicio, Propiedades, Agentes) ahora tienen un sutil efecto de vidrio esmerilado, en línea con los botones de búsqueda, notificaciones y carrito. Se ve más moderno y prolijo, y se adapta al modo claro/oscuro."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Propiedades Destacadas al inicio",
    "items": [
      {
        "type": "mejora",
        "text": "En la página de inicio, las Propiedades Destacadas ahora aparecen primero, antes de las secciones \"Cómo Funciona\" y \"Tipos de Propiedad\"."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Homepage del sitio web actualizado",
    "items": [
      {
        "type": "mejora",
        "text": "Las tres tarjetas de acceso rápido ahora son Comprar, Vender y Alquilar (antes había dos veces Comprar). La tarjeta Vender lleva a la página de contacto."
      },
      {
        "type": "mejora",
        "text": "Las Propiedades Destacadas se muestran en una grilla de hasta 9 propiedades, en lugar del carrusel anterior."
      },
      {
        "type": "mejora",
        "text": "En la sección Conviértete en Agente, el botón ahora abre WhatsApp para contactar directamente, en lugar de ir al registro."
      },
      {
        "type": "mejora",
        "text": "Se quitaron del inicio las secciones \"Cientos de Socios en Todo el Mundo\" y \"Últimos Artículos\" para una página más enfocada."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Detalle de propiedad arranca desde arriba",
    "items": [
      {
        "type": "arreglo",
        "text": "En el sitio web, al entrar al detalle de una propiedad desde el listado, la página ahora se abre desde el principio. Antes aparecía a la mitad del scroll, manteniendo la posición de la página anterior."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Ocultar agentes del sitio web",
    "items": [
      {
        "type": "nuevo",
        "text": "En el detalle de cada agente (panel de administración) ahora hay un botón Activo/Inactivo para mostrar u ocultar al agente del sitio web. Los agentes marcados como Inactivos dejan de aparecer en el listado y la página de agentes del sitio público."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Menú del sitio web mejor distribuido",
    "items": [
      {
        "type": "mejora",
        "text": "Los botones del menú principal del sitio web ahora se reparten de forma pareja a lo ancho de la barra, en lugar de quedar agrupados y descentrados. Se ve más prolijo y equilibrado."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Menú del sitio web más simple",
    "items": [
      {
        "type": "mejora",
        "text": "Se simplificó el menú principal del sitio web: se quitaron los botones Inmobiliarias, Páginas y Blog para dejar la navegación más clara y enfocada en lo importante."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Mapa de la propiedad en pantalla completa",
    "items": [
      {
        "type": "nuevo",
        "text": "En el detalle de la propiedad (sitio web, panel de admin y panel de agentes) ahora podés tocar el botón \"Ampliar\" sobre el mapa para abrirlo en grande, navegar la zona y hacer zoom con comodidad. Se cierra con la X o la tecla Escape."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Fotos más grandes en pantalla completa",
    "items": [
      {
        "type": "mejora",
        "text": "Al abrir una foto de la propiedad en pantalla completa, ahora la imagen ocupa una porción mucho mayor de la pantalla, para verla con más detalle."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Footer del sitio web renovado",
    "items": [
      {
        "type": "mejora",
        "text": "Se rediseñó el pie de página del sitio web: ahora muestra el logo de Anabella Luna, datos de contacto reales (dirección, teléfono y email) y solo las redes sociales que estén configuradas."
      },
      {
        "type": "mejora",
        "text": "Se quitó la sección que invitaba a descargar una app móvil y los enlaces de ejemplo que venían del diseño original (ciudades y datos ficticios)."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Galería de propiedades sin avance automático",
    "items": [
      {
        "type": "arreglo",
        "text": "En el detalle de la propiedad del sitio web, el carrusel de fotos ya no cambia solo. Ahora podés mirar cada imagen con tranquilidad y avanzar manualmente cuando quieras."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Panel de agentes más enfocado",
    "items": [
      {
        "type": "mejora",
        "text": "Se quitaron los recuadros de Equipo de Agentes, Comisiones y Asignaciones, Roles y Permisos y Distribución por Zonas del panel de agentes. El dashboard queda más limpio y centrado en las métricas y el rendimiento del equipo."
      }
    ]
  },
  {
    "date": "2026-06-21",
    "title": "Panel de clientes más simple",
    "items": [
      {
        "type": "mejora",
        "text": "Se quitaron los recuadros de Lead Scoring y Comunicación Integrada del panel de clientes. Ahora la Base de Datos de Clientes ocupa todo el ancho para verse más clara."
      }
    ]
  },
  {
    "date": "2026-06-19",
    "title": "Visitas a propiedades de colegas",
    "items": [
      {
        "type": "nuevo",
        "text": "Al agendar una visita ahora podés indicar que la propiedad es de un colega u otra inmobiliaria: se cargan el nombre y la dirección de la propiedad y la inmobiliaria a cargo, sin necesidad de que esté publicada en el sistema."
      }
    ]
  },
  {
    "date": "2026-06-19",
    "title": "Operaciones y comisiones conectadas",
    "items": [
      {
        "type": "arreglo",
        "text": "Las ventas y alquileres cargados desde el panel de agentes ahora quedan guardados correctamente como operaciones reales."
      },
      {
        "type": "mejora",
        "text": "Las comisiones se actualizan con el monto de la operación, el porcentaje del agente y la fecha de cierre o cobro."
      }
    ]
  },
  {
    "date": "2026-06-18",
    "title": "Recompensas conectadas a datos reales",
    "items": [
      {
        "type": "arreglo",
        "text": "Los gráficos, rankings y premios de Recompensas ahora se calculan con operaciones, comisiones y propiedades reales de la base de datos."
      },
      {
        "type": "mejora",
        "text": "Al cerrar o editar una operación, el sistema completa los datos necesarios para que las recompensas se actualicen correctamente."
      }
    ]
  },
  {
    "date": "2026-06-18",
    "title": "Estado no disponible en propiedades",
    "items": [
      {
        "type": "nuevo",
        "text": "Al crear o editar una propiedad ahora podés marcar el estado como \"No disponible\"."
      },
      {
        "type": "mejora",
        "text": "Las propiedades marcadas como \"No disponible\" quedan automáticamente fuera del sitio web público."
      }
    ]
  },
  {
    "date": "2026-06-18",
    "title": "Sitio web y WhatsApp más prolijos",
    "items": [
      {
        "type": "arreglo",
        "text": "En el sitio web, las fotos de portada de las propiedades ya no muestran una franja gris oscura en la base de la imagen."
      },
      {
        "type": "mejora",
        "text": "WhatsApp queda incluido en las novedades para comunicar mejor las mejoras y correcciones recientes del canal de contacto."
      }
    ]
  },
  {
    "date": "2026-06-12",
    "title": "Mapas nuevos en propiedades",
    "items": [
      {
        "type": "mejora",
        "text": "La vista de Mapa de propiedades estrena mapas nuevos, más rápidos y detallados, con un marcador por cada propiedad publicada."
      },
      {
        "type": "mejora",
        "text": "Al cargar o editar una propiedad podés arrastrar el pin sobre el mapa para ajustar la ubicación exacta antes de guardar."
      }
    ]
  },
  {
    "date": "2026-06-12",
    "title": "Carga de propiedades sin campos obligatorios",
    "items": [
      {
        "type": "mejora",
        "text": "El formulario de nueva propiedad ya no exige campos obligatorios: podés guardar con los datos que tengas a mano y completar el resto cuando quieras, sin trabas en el flujo de trabajo."
      },
      {
        "type": "mejora",
        "text": "Si guardás sin título, el sistema arma uno automáticamente con el tipo de propiedad, la operación y el barrio (por ejemplo: \"Departamento en Venta · Palermo\")."
      }
    ]
  },
  {
    "date": "2026-06-12",
    "title": "Compartir propiedades por WhatsApp",
    "items": [
      {
        "type": "arreglo",
        "text": "Los links de propiedades que se copian desde el panel ahora muestran la vista previa completa al compartirlos por WhatsApp, también desde iPhone: foto de portada grande arriba y, debajo, el precio, la dirección, los ambientes, los amenities y la descripción."
      }
    ]
  },
  {
    "date": "2026-06-11",
    "title": "Carga de propiedades más simple y ubicación exacta",
    "items": [
      {
        "type": "mejora",
        "text": "El alta y la edición de propiedades ahora son una sola pantalla: los datos de la propiedad y la asignación del cliente quedaron juntos, sin tener que pasar por un \"paso 2\" aparte."
      },
      {
        "type": "nuevo",
        "text": "La dirección se carga en dos campos separados, calle y altura (número). Al completar la altura, el mapa ubica el pin en la posición exacta de la propiedad."
      }
    ]
  },
  {
    "date": "2026-06-11",
    "title": "Consultas del sitio web y portales inmobiliarios",
    "items": [
      {
        "type": "nuevo",
        "text": "Nueva sección Consultas: ahora podés ver y hacer seguimiento de todas las consultas que llegan desde el sitio web, con estados para saber cuáles ya fueron respondidas."
      },
      {
        "type": "nuevo",
        "text": "Integraciones con portales: las propiedades pueden publicarse automáticamente en 12 portales inmobiliarios (Zonaprop, Argenprop, Proppit y más) mediante feeds que se actualizan solos."
      },
      {
        "type": "arreglo",
        "text": "Solucionamos un error que dejaba el panel de administración fuera de servicio."
      }
    ]
  },
  {
    "date": "2026-06-09",
    "title": "Operaciones y comisiones",
    "items": [
      {
        "type": "arreglo",
        "text": "Las comisiones ahora se calculan correctamente según quién las mire: el administrador ve el total y cada agente ve solo lo suyo."
      },
      {
        "type": "mejora",
        "text": "Al editar una operación se abre el mismo formulario completo que al crearla, con todos los datos cargados."
      }
    ]
  },
  {
    "date": "2026-06-08",
    "title": "Historial de operaciones y fotos renovadas",
    "items": [
      {
        "type": "nuevo",
        "text": "Las operaciones ahora se pueden editar y eliminar, y hay una tabla con el historial completo."
      },
      {
        "type": "mejora",
        "text": "Las fotos de las propiedades se muestran en un nuevo visor tipo presentación, más grande y moderno."
      }
    ]
  },
  {
    "date": "2026-06-07",
    "title": "Tours virtuales 360",
    "items": [
      {
        "type": "mejora",
        "text": "Los tours 360 ahora tienen botón de pantalla completa (estilo YouTube) y se ven mejor integrados en la página."
      }
    ]
  },
  {
    "date": "2026-06-06",
    "title": "Filtros por agente y mejoras en WhatsApp",
    "items": [
      {
        "type": "nuevo",
        "text": "Filtro por agente en Propiedades y en Clientes: elegí un agente y mirá solo lo que le pertenece."
      },
      {
        "type": "nuevo",
        "text": "En la Bandeja de WhatsApp ahora se pueden eliminar conversaciones."
      },
      {
        "type": "mejora",
        "text": "La configuración de WhatsApp se movió a la página de Integraciones para tener todo en un solo lugar."
      }
    ]
  }
];

export default CHANGELOG_ENTRIES;
